# create a workflow that runs scrape.py once every hour
name: Main

# Trigger the workflow every hour, manually or when pushing to the main branch
on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

# also support manual triggering


jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository so that we have access to the Python script
      - name: Check out the code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify your required Python version

      # Install dependencies (if any)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      # Authenticate to Google Cloud
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      # Check if authentication succeeded
      - name: 'Check Google Cloud Authentication Status'
        if: failure()
        run: exit 1

        
      # Run the Python script
      - name: Run cron.py
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GEOCODING_BASE_URL: ${{ vars.GEOCODING_BASE_URL }}
          DRIVEBC_MAJOR_EVENTS_URL: ${{ vars.DRIVEBC_MAJOR_EVENTS_URL }}

          MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
          MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
          MONGODB_HOST: ${{ secrets.MONGODB_HOST }}
          MONGODB_DBNAME: ${{ secrets.MONGODB_DBNAME }}
          MONGODB_COLLECTIONNAME: ${{ secrets.MONGDODB_COLLECTIONNAME }}

          CLOUD_STORAGE_BUCKET_NAME: ${{ secrets.CLOUD_STORAGE_BUCKET_NAME }}
          # GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: python cron.py
      # Automatically update data.json
      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
            file-path: src/data/data.json
            commit-msg: update data.json
            github-token: ${{ secrets.GH_TOKEN }}
